[package]
authors = ["Raclett3 <im@s283.net>"]
edition = "2018"
name = "minnet-rs"
version = "0.1.0"

[dependencies]
actix-web = {version = "3"}
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
toml = "0.5"
